# -*- coding: utf-8 -*-
"""Tourism_Domain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13W6C73b24IOjJGqFE0GLFBkZygSr8WLq

# data collection
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/travel_dataset.csv')
df.head()

"""# data preprocessing"""

df.shape

df.info()

df.isnull().sum()

df.fillna(df.median(numeric_only=True), inplace=True)
df['TypeofContact'].fillna(df['TypeofContact'].mode()[0], inplace=True)

df.isnull().sum()

df.shape

df.describe()

df.drop('CustomerID',axis = 1, inplace = True)

num_cols = ['Age', 'MonthlyIncome', 'DurationOfPitch', 'NumberOfFollowups']
for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f'{col}')
    plt.show()

cat_cols = ['TypeofContact', 'ProductPitched', 'Occupation']
for col in cat_cols:
    plt.figure(figsize=(10,5))
    sns.countplot(data=df, x=col, hue='ProdTaken')
    plt.title(f'{col} distribution by ProdTaken')
    plt.legend(title='ProdTaken')
    plt.show()

num_cols = ['Age', 'MonthlyIncome', 'DurationOfPitch', 'NumberOfFollowups',
            'PreferredPropertyStar', 'NumberOfTrips', 'PitchSatisfactionScore',
            'NumberOfChildrenVisiting']

plt.figure(figsize=(16, 8))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, 4, i)
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df[num_cols + ['ProdTaken']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

df['Gender'].unique()

df['Gender'] = df['Gender'].replace('Fe Male', 'Female')

df['Gender'].unique()

df['Gender'] = df['Gender'].replace({'Female':0, 'Male':1})

df['TypeofContact'].unique() # onehot

from sklearn.preprocessing import OneHotEncoder

onc_hot = OneHotEncoder(sparse_output=False)
transform_contact = pd.DataFrame(onc_hot.fit_transform(df[['TypeofContact']]),
                                 columns = onc_hot.get_feature_names_out(['TypeofContact']))
df[transform_contact.columns] = transform_contact

df['MaritalStatus'].unique() # onehot

onc_hot = OneHotEncoder(sparse_output=False)
transform_Marital = pd.DataFrame(onc_hot.fit_transform(df[['MaritalStatus']]),
                                 columns = onc_hot.get_feature_names_out(['MaritalStatus']))
df[transform_Marital.columns] = transform_Marital

df.drop(['TypeofContact','MaritalStatus'],axis=1,inplace = True)

df['Occupation'].unique() # ordinal encoder

df['ProductPitched'].unique() # ordinal encoder

df['Designation'].unique() # ordinal encoder

from sklearn.preprocessing import OrdinalEncoder

odr_enc = OrdinalEncoder(categories=[['Free Lancer','Small Business','Salaried','Large Business'],
 ['Basic','Standard','Deluxe','Super Deluxe','King'],['Executive','Manager','Senior Manager','AVP','VP']])
transform_ordinal = pd.DataFrame(odr_enc.fit_transform(df[['Occupation','ProductPitched','Designation']]),
                                 columns = odr_enc.get_feature_names_out(['Occupation','ProductPitched','Designation']))
df[transform_ordinal.columns] = transform_ordinal

df

"""# segerate input's and output's"""

y = df['ProdTaken']
x = df.drop('ProdTaken', axis=1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
x_train = pd.DataFrame(x_train_scaled, columns=x_train.columns, index=x_train.index)
x_test = pd.DataFrame(x_test_scaled, columns=x_test.columns, index=x_test.index)

"""# model building"""

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, roc_curve,auc
from sklearn.model_selection import RandomizedSearchCV

"""# logistic model buliding"""

logistc = LogisticRegression()
logistc.fit(x_train, y_train)

y_test_pred = logistc.predict(x_test)
y_test_pred

print("Training Score:", logistc.score(x_train, y_train))
print("Testing Score:", logistc.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning LogisticRegression model"""

pram_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'penalty': ['l1', 'l2'],
    'max_iter': [100, 200, 300, 400, 500]
}

grid = RandomizedSearchCV(LogisticRegression(),cv = 5, param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

logistic_tuning = grid.best_estimator_

print("Training Score:", logistic_tuning.score(x_train, y_train))
print("Testing Score:", logistic_tuning.score(x_test, y_test))

"""## KNN model buliding"""

KNN = KNeighborsClassifier()
KNN.fit(x_train, y_train)

y_test_pred = KNN.predict(x_test)
y_test_pred

print("Training Score:", KNN.score(x_train, y_train))
print("Testing Score:", KNN.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning for KNN model"""

pram_grid = {
    'n_neighbors': range(1, 21),
    'weights': ['uniform', 'distance']
}

grid = RandomizedSearchCV(KNeighborsClassifier(),cv = 5, param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

KNN_tuning = KNeighborsClassifier(n_neighbors=1, weights='distance')
KNN_tuning.fit(x_train, y_train)

print("Training Score:", KNN_tuning.score(x_train, y_train))
print("Testing Score:", KNN_tuning.score(x_test, y_test))

"""## decision tree model"""

DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)

y_test_pred = DT.predict(x_test)
y_test_pred

print("Training Score:", DT.score(x_train, y_train))
print("Testing Score:", DT.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the DT model"""

grid_pram = {
    'criterion': ['gini', 'entropy'],
    'max_depth': range(1,10,1),
    'min_samples_split': range(2,10,1),
    'min_samples_leaf': range(1,10,1),
}

grid = RandomizedSearchCV(DecisionTreeClassifier(),cv = 5,param_distributions = grid_pram)
grid.fit(x_train, y_train)

print(grid.best_params_)

DT_tuning = grid.best_estimator_

print("Training Score:", DT_tuning.score(x_train, y_train))
print("Testing Score:", DT_tuning.score(x_test, y_test))

"""## RandomForest model"""

RF = RandomForestClassifier()
RF.fit(x_train, y_train)

y_test_pred = RF.predict(x_test)
y_test_pred

print("Training Score:", RF.score(x_train, y_train))
print("Testing Score:", RF.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the RandomForest model"""

grid_pram = {
    'n_estimators': range(10,100,10),
    'max_depth': range(1,10,1),
    'min_samples_split': range(2,10,1),
    'min_samples_leaf': range(1,10,1),
}

grid = RandomizedSearchCV(RandomForestClassifier(),cv = 5,param_distributions = grid_pram)
grid.fit(x_train, y_train)

print(grid.best_params_)

rf_tuning  = RandomForestClassifier(n_estimators=90, min_samples_split=4, min_samples_leaf=9, max_depth=10)
rf_tuning.fit(x_train, y_train)

print("Training Score:", rf_tuning.score(x_train, y_train))
print("Testing Score:", rf_tuning.score(x_test, y_test))

"""## SVM"""

SVM = SVC()
SVM.fit(x_train, y_train)

y_test_pred = SVM.predict(x_test)
y_test_pred

print("Training Score:", SVM.score(x_train, y_train))
print("Testing Score:", SVM.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the SVC model"""

pram_grid = {
    'C': [0.1, 1, 10, 12],
    'gamma': [1, 0.1, 0.01, 0.001],
}

grid = RandomizedSearchCV(SVC(),cv = 5,param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

svc_tuning = SVC(C=10, gamma=0.1)
svc_tuning.fit(x_train, y_train)

print("Training Score:", svc_tuning.score(x_train, y_train))
print("Testing Score:", svc_tuning.score(x_test, y_test))

